language: ruby
rvm:
  2.4.0

env:
- MITTSU_LIBGLFW_PATH=/usr/local/lib MITTSU_LIBGLFW_FILE=libglfw.so MINITEST_REPORTER=JUnitReporter

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo apt-get update; sudo apt-get install xorg-dev libgl1-mesa-dev
  - bash ./install-glfw-3.1.2.sh

script: bundle exec rake test
