jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    steps:
      ## SETUP
      - run: chruby 2.3.7
      - run: brew install glfw
      - run: bundle install
      
      ## TEST
      - run:
          name: Run tests
          command: bundle exec rake test
          environment:
            MITTSU_LIBGLFW_PATH: /usr/local/lib
            MITTSU_LIBGLFW_FILE: libglfw.dylib
            MINITEST_REPORTER: JUnitReporter

      ## COLLECT RESULTS
      - run: bundle exec codeclimate-test-reporter
      - run:
          name: Collect test results
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/minitest/
            cp -r test/reports/*.xml $CIRCLE_TEST_REPORTS/minitest/
      - store_test_results:
          path: test/reports